### ISSUE TITLE
Format indent wrong

### ISSUE THREAD

**Issue by mikenovikov** [aswinkumar863/smarty-vscode-support#43]
**Description**
Format not working when adjacent html tags has extra new lines (2+ line breaks) around them (the formatter is creating new lines around head and body on format).

Is ok:
```html
<div>
 {...smarty code...}
</div> 
<div>
 {...smarty code...}
</div> 
```
Is not ok:
```html
<div>
 {...smarty code...}
</div> 

<div>
 {...smarty code...}
</div> 
```

**To Reproduce**
1. Create full html page.
2. Insert some arbitary code insde body.
3. Format document.
4. See how it is not working.

**Screenshots**
![smarty](https://user-images.githubusercontent.com/4421441/87258453-4a687480-c4ac-11ea-9cb7-25ccf2a54eeb.gif)
(Command-Option-L on the screen means Format Code.)

**Context:**
 - VSCode: v1.47.0
 - Extension: v1.6.0

**Comment by aswinkumar863** [comment]
Fixed with commit 77b55fdd393c5603aa453725d34281db324b6256

**Comment by mikenovikov** [comment]
Nope, still not working.
 
VSCode version: 1.47.3
Extension version: v1.7.1

Try this markup:
```html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <ul>
      {foreach $items as $item}
      {if $item.name}
      <li>{$item.name}</li>
      {/if}
      {/foreach}
    </ul>
  </body>

</html>
```

Should be: 
```html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <ul>
      {foreach $items as $item}
        {if $item.name}
          <li>{$item.name}</li>
        {/if}
      {/foreach}
    </ul>
  </body>

</html>
```

**Comment by aswinkumar863** [comment]
@mikenovikov you have to check up that any other formatter extension or user setting causing the issue. One way to do is that disable all installed extension except Smarty Template Support and comment out the user `settings.json` completely. I hope the problem should vanish.
